apiVersion: typeform.krateo.io/v1alpha1
kind: ProviderConfig
metadata:
  name: provider-typeform-config
spec:
  verbose: false
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: typeform.com-secret
      key: token
